SELECT ID "id" , TO_CHAR(VISIT_DATE,'YYYY-MM-DD') "visit_date" , PEOPLE "people" 
from 
(SELECT ID , VISIT_DATE, PEOPLE , COUNT(*) OVER (PARTITION BY ID-ROWNUM ORDER BY ID-ROWNUM ) AS CNTER FROM STADIUM WHERE PEOPLE >= 100 ) SS WHERE CNTER >=3 ORDER BY VISIT_DATE